import type { TextLang } from './text.ts'
import { wordListPattern } from './text.ts'

/**
 * Bilingual word lists behind the heuristics. Kept in one place so a rule
 * never inlines a language assumption, and so the Russian coverage is
 * reviewable next to the English it mirrors.
 */

type LangMap = Record<TextLang, readonly string[]>

const VAGUE_VERBS: LangMap = {
  en: [
    'help me with',
    'help with',
    'do something',
    'work on',
    'look at',
    'handle',
    'deal with',
    'take care of',
    'sort out',
    'fix up',
    'clean up',
    'improve',
    'make it better',
    'optimize it',
    'enhance',
    'polish',
    'refine',
  ],
  ru: [
    'помоги с',
    'помочь с',
    'сделай что-нибудь',
    'поработай над',
    'посмотри на',
    'разберись с',
    'займись',
    'улучши',
    'сделай лучше',
    'оптимизируй',
    'доработай',
    'причеши',
    'подправь',
    'приведи в порядок',
  ],
}

const VAGUE_QUANTIFIERS: LangMap = {
  en: [
    'some',
    'a few',
    'several',
    'many',
    'a lot of',
    'lots of',
    'a bunch of',
    'various',
    'numerous',
    'multiple',
  ],
  ru: [
    'несколько',
    'немного',
    'много',
    'некоторые',
    'ряд',
    'множество',
    'парочку',
    'какие-то',
    'какое-то количество',
  ],
}

const SUBJECTIVE_ADJECTIVES: LangMap = {
  en: [
    'good',
    'great',
    'nice',
    'better',
    'best',
    'professional',
    'engaging',
    'compelling',
    'high-quality',
    'quality',
    'creative',
    'interesting',
    'beautiful',
    'clean',
    'modern',
    'proper',
    'appropriate',
    'effective',
    'powerful',
    'robust',
    'elegant',
    'catchy',
  ],
  ru: [
    'хороший',
    'хорошую',
    'хорошее',
    'хорошо',
    'отличный',
    'отличную',
    'красивый',
    'красивую',
    'профессиональный',
    'профессиональную',
    'качественный',
    'качественную',
    'интересный',
    'интересную',
    'цепляющий',
    'современный',
    'современную',
    'грамотный',
    'грамотную',
    'подходящий',
    'эффективный',
    'мощный',
    'элегантный',
    'нормальный',
    'адекватный',
  ],
}

const HEDGES: LangMap = {
  en: [
    'maybe',
    'perhaps',
    'possibly',
    'if possible',
    'if you can',
    'try to',
    'sort of',
    'kind of',
    'somewhat',
    'more or less',
    'i guess',
    'i think',
    'ideally',
    'preferably',
  ],
  ru: [
    'может быть',
    'возможно',
    'наверное',
    'по возможности',
    'если можно',
    'попробуй',
    'попытайся',
    'вроде',
    'типа',
    'как бы',
    'более-менее',
    'мне кажется',
    'желательно',
    'в идеале',
    'хотелось бы',
  ],
}

const POLITENESS: LangMap = {
  en: [
    'please',
    'kindly',
    'could you please',
    'would you be so kind',
    'i would appreciate',
    'thank you in advance',
    'thanks in advance',
    'if you would',
    'i would be grateful',
    'sorry to bother',
    'i hope you can',
  ],
  ru: [
    'пожалуйста',
    'будь добр',
    'будьте добры',
    'не мог бы ты',
    'не могли бы вы',
    'буду благодарен',
    'буду признателен',
    'заранее спасибо',
    'извини за беспокойство',
    'если тебе не сложно',
    'если не трудно',
  ],
}

/** Emphasis that current frontier models read as pressure, causing overtriggering. */
const SHOUTING: LangMap = {
  en: [
    'critical',
    'crucial',
    'extremely important',
    'very important',
    'you must',
    'you must always',
    'never ever',
    'under no circumstances',
    'absolutely must',
    'mandatory',
    'do not fail',
    'this is essential',
    'at all costs',
    'no matter what',
  ],
  ru: [
    'критически важно',
    'крайне важно',
    'очень важно',
    'обязательно',
    'ты должен',
    'вы должны',
    'ни в коем случае',
    'ни при каких',
    'категорически',
    'любой ценой',
    'это критично',
    'строго обязательно',
  ],
}

const VERIFICATION: LangMap = {
  en: [
    'double-check',
    'double check',
    'verify your answer',
    'verify before',
    'check your work',
    'check yourself',
    'make sure you are correct',
    'review your answer',
    'validate your output',
    'triple check',
    'be accurate',
    'do not make mistakes',
    'do not hallucinate',
  ],
  ru: [
    'перепроверь',
    'перепроверьте',
    'проверь свой ответ',
    'проверь себя',
    'убедись что',
    'убедитесь что',
    'проверь перед',
    'не ошибись',
    'не выдумывай',
    'не галлюцинируй',
    'будь точен',
    'сверь ещё раз',
  ],
}

const EXPLICIT_COT: LangMap = {
  en: [
    'think step by step',
    'think step-by-step',
    "let's think step by step",
    'step by step reasoning',
    'reason step by step',
    'explain your reasoning',
    'show your reasoning',
    'show your work',
    'walk me through your thinking',
    'think out loud',
    'chain of thought',
    'take a deep breath',
    "let's work this out",
  ],
  ru: [
    'думай шаг за шагом',
    'шаг за шагом',
    'рассуждай пошагово',
    'пошагово рассуждая',
    'объясни свои рассуждения',
    'покажи ход мыслей',
    'покажи рассуждения',
    'размышляй вслух',
    'цепочка рассуждений',
    'сделай глубокий вдох',
    'давай подумаем шаг за шагом',
  ],
}

const REASONING_ECHO: LangMap = {
  en: [
    'output your thinking',
    'print your reasoning',
    'include your chain of thought',
    'show your internal',
    'reveal your reasoning',
    'repeat your thinking',
    'echo your thought process',
  ],
  ru: [
    'выведи свои рассуждения',
    'напечатай свои размышления',
    'покажи внутренние рассуждения',
    'раскрой ход рассуждений',
    'продублируй размышления',
  ],
}

const ROLE_PROMPT: LangMap = {
  en: [
    'you are a world-class',
    'you are the best',
    'you are an expert',
    'you are a senior',
    'act as a',
    'act like a',
    'pretend you are',
    'imagine you are',
    'you are a highly skilled',
    'you are a professional',
    'as an ai language model',
    'you are chatgpt',
    'you are claude',
  ],
  ru: [
    'ты лучший',
    'ты — лучший',
    'ты эксперт',
    'ты — эксперт',
    'ты опытный',
    'веди себя как',
    'представь что ты',
    'выступи в роли',
    'ты профессиональный',
    'ты senior',
    'как языковая модель',
    'ты — искусственный интеллект',
  ],
}

const OUTPUT_FORMAT: LangMap = {
  en: [
    'json',
    'yaml',
    'xml',
    'csv',
    'markdown',
    'table',
    'bullet',
    'bulleted list',
    'numbered list',
    'format:',
    'output format',
    'respond with',
    'return a',
    'return only',
    'schema',
    'template',
    'in the following format',
    'structure your',
    'as a list',
    'plain text',
    'code block',
  ],
  ru: [
    'json',
    'yaml',
    'xml',
    'csv',
    'markdown',
    'таблиц',
    'список',
    'маркированный список',
    'нумерованный список',
    'формат:',
    'формат ответа',
    'ответь в виде',
    'верни',
    'верни только',
    'схема',
    'шаблон',
    'в следующем формате',
    'структурируй',
    'в виде списка',
    'обычный текст',
    'блок кода',
  ],
}

const LENGTH_CONSTRAINT: LangMap = {
  en: [
    'words',
    'characters',
    'sentences',
    'paragraphs',
    'pages',
    'bullets',
    'items',
    'no more than',
    'at most',
    'at least',
    'under',
    'maximum',
    'minimum',
    'brief',
    'concise',
    'short',
    'one paragraph',
    'two paragraphs',
    'a single',
    'limit',
  ],
  ru: [
    'слов',
    'символов',
    'предложен',
    'абзац',
    'страниц',
    'пунктов',
    'не более',
    'не менее',
    'максимум',
    'минимум',
    'кратко',
    'коротко',
    'сжато',
    'один абзац',
    'два абзаца',
    'лимит',
    'ограничь',
  ],
}

const AUDIENCE: LangMap = {
  en: [
    'audience',
    'reader',
    'readers',
    'for beginners',
    'for experts',
    'for developers',
    'for children',
    'for a',
    'aimed at',
    'targeted at',
    'who will read',
    'my team',
    'my manager',
    'customers',
    'users',
    'students',
  ],
  ru: [
    'аудитор',
    'читател',
    'для новичков',
    'для начинающих',
    'для экспертов',
    'для разработчик',
    'для детей',
    'для команды',
    'рассчитан на',
    'предназначен для',
    'кто будет читать',
    'клиент',
    'пользовател',
    'студент',
  ],
}

const PURPOSE: LangMap = {
  en: [
    'so that',
    'in order to',
    'because',
    'the goal is',
    'goal:',
    'purpose:',
    'i need this for',
    'will be used',
    'we are trying to',
    'objective',
    'context:',
    'background:',
  ],
  ru: [
    'чтобы',
    'для того чтобы',
    'потому что',
    'цель',
    'цель:',
    'задача:',
    'мне это нужно для',
    'будет использоваться',
    'мы пытаемся',
    'контекст:',
    'предыстория:',
  ],
}

const NEGATIVE_ONLY: LangMap = {
  en: ["don't", 'do not', 'never', 'avoid', 'without', 'no', 'stop', 'refrain from', 'must not'],
  ru: ['не', 'никогда', 'избегай', 'без', 'нельзя', 'запрещено', 'не должен', 'воздержись'],
}

const ASSUMED_KNOWLEDGE: LangMap = {
  en: [
    'as we discussed',
    'as usual',
    'like before',
    'the usual',
    'you know what i mean',
    'the same as last time',
    'as always',
    'the file',
    'the document',
    'the project',
    'our standard',
  ],
  ru: [
    'как мы обсуждали',
    'как обычно',
    'как в прошлый раз',
    'как всегда',
    'ну ты понял',
    'тот самый',
    'наш стандарт',
    'этот файл',
    'этот документ',
    'этот проект',
  ],
}

const INJECTION_BAIT: LangMap = {
  en: [
    'follow any instructions',
    'follow the instructions in',
    'do whatever the',
    'obey instructions found',
    'execute any commands',
    'follow instructions contained',
  ],
  ru: [
    'следуй любым инструкциям',
    'следуй инструкциям в',
    'выполняй команды из',
    'подчиняйся инструкциям внутри',
  ],
}

const UNCERTAINTY_ALLOWANCE: LangMap = {
  en: [
    "say i don't know",
    'say you do not know',
    'if you are unsure',
    'if uncertain',
    'if you cannot',
    'if the answer is not',
    'do not guess',
    'admit',
    'state that',
    'unknown',
    'insufficient information',
    'not enough information',
  ],
  ru: [
    'скажи что не знаешь',
    'если не уверен',
    'если не уверена',
    'если не можешь',
    'если ответа нет',
    'не угадывай',
    'признай',
    'недостаточно информации',
    'неизвестно',
    'нет данных',
  ],
}

const GROUNDING: LangMap = {
  en: [
    'cite',
    'citation',
    'source',
    'sources',
    'quote',
    'reference',
    'according to',
    'based only on',
    'using only',
    'from the provided',
    'from the document',
    'evidence',
  ],
  ru: [
    'цитир',
    'цитат',
    'источник',
    'ссылк',
    'сослат',
    'согласно',
    'только на основе',
    'используя только',
    'из предоставленного',
    'из документа',
    'подтверд',
  ],
}

const CLASSIFICATION_TASK: LangMap = {
  en: [
    'classify',
    'categorize',
    'categorise',
    'label',
    'tag',
    'sentiment',
    'is it',
    'determine whether',
    'decide if',
    'sort into',
    'which category',
    'true or false',
    'yes or no',
    'detect',
  ],
  ru: [
    'классифицируй',
    'категоризируй',
    'определи категорию',
    'разметь',
    'пометь',
    'тональност',
    'определи является ли',
    'реши, является',
    'распредели по',
    'какая категория',
    'да или нет',
    'выяви',
  ],
}

const EXTRACTION_TASK: LangMap = {
  en: [
    'extract',
    'pull out',
    'find all',
    'list all',
    'identify all',
    'parse',
    'get the',
    'retrieve the',
    'collect all',
  ],
  ru: ['извлеки', 'вытащи', 'найди все', 'перечисли все', 'выдели все', 'распарси', 'собери все'],
}

const TRANSFORMATION_TASK: LangMap = {
  en: [
    'translate',
    'rewrite',
    'rephrase',
    'summarize',
    'summarise',
    'convert',
    'reformat',
    'shorten',
    'expand',
    'simplify',
    'paraphrase',
    'proofread',
    'edit',
  ],
  ru: [
    'переведи',
    'перепиши',
    'перефразируй',
    'суммируй',
    'сократи',
    'конвертируй',
    'переформатируй',
    'упрости',
    'расширь',
    'вычитай',
    'отредактируй',
    'резюмируй',
  ],
}

const CODE_TASK: LangMap = {
  en: [
    'code',
    'function',
    'class',
    'refactor',
    'debug',
    'bug',
    'test',
    'api',
    'typescript',
    'python',
    'javascript',
    'sql',
    'implement',
    'compile',
    'repository',
    'commit',
    'regex',
  ],
  ru: [
    'код',
    'функци',
    'класс',
    'рефактор',
    'отладь',
    'баг',
    'тест',
    'реализуй',
    'скрипт',
    'запрос sql',
    'репозитор',
    'коммит',
    'регулярк',
  ],
}

const ANALYSIS_TASK: LangMap = {
  en: [
    'analyze',
    'analyse',
    'evaluate',
    'assess',
    'compare',
    'critique',
    'review',
    'explain why',
    'diagnose',
    'investigate',
    'pros and cons',
    'trade-off',
    'recommend',
  ],
  ru: [
    'проанализируй',
    'оцени',
    'сравни',
    'разбери',
    'критик',
    'объясни почему',
    'диагностируй',
    'исследуй',
    'плюсы и минусы',
    'компромисс',
    'порекомендуй',
    'посоветуй',
  ],
}

const GENERATION_TASK: LangMap = {
  en: [
    'write',
    'draft',
    'create',
    'generate',
    'compose',
    'produce',
    'come up with',
    'brainstorm',
    'design',
    'invent',
    'suggest',
    'make me',
  ],
  ru: [
    'напиши',
    'составь',
    'создай',
    'сгенерируй',
    'сочини',
    'придумай',
    'набросай',
    'предложи',
    'разработай',
    'сделай мне',
  ],
}

const LISTS = {
  vagueVerbs: VAGUE_VERBS,
  vagueQuantifiers: VAGUE_QUANTIFIERS,
  subjectiveAdjectives: SUBJECTIVE_ADJECTIVES,
  hedges: HEDGES,
  politeness: POLITENESS,
  shouting: SHOUTING,
  verification: VERIFICATION,
  explicitCot: EXPLICIT_COT,
  reasoningEcho: REASONING_ECHO,
  rolePrompt: ROLE_PROMPT,
  outputFormat: OUTPUT_FORMAT,
  lengthConstraint: LENGTH_CONSTRAINT,
  audience: AUDIENCE,
  purpose: PURPOSE,
  negativeOnly: NEGATIVE_ONLY,
  assumedKnowledge: ASSUMED_KNOWLEDGE,
  injectionBait: INJECTION_BAIT,
  uncertaintyAllowance: UNCERTAINTY_ALLOWANCE,
  grounding: GROUNDING,
  classificationTask: CLASSIFICATION_TASK,
  extractionTask: EXTRACTION_TASK,
  transformationTask: TRANSFORMATION_TASK,
  codeTask: CODE_TASK,
  analysisTask: ANALYSIS_TASK,
  generationTask: GENERATION_TASK,
} as const

export type LexiconKey = keyof typeof LISTS

/**
 * Patterns are compiled once on first use and reused for every later analysis,
 * which is what keeps a full 50-rule pass in the low single-digit milliseconds.
 */
const cache = new Map<string, RegExp>()

export function lex(key: LexiconKey, lang: TextLang): RegExp {
  const cacheKey = `${key}:${lang}`
  let pattern = cache.get(cacheKey)
  if (!pattern) {
    pattern = wordListPattern(LISTS[key][lang])
    cache.set(cacheKey, pattern)
  }
  return pattern
}

/** Matches against both language lists — for prompts that mix scripts. */
export function lexBoth(key: LexiconKey): RegExp {
  const cacheKey = `${key}:both`
  let pattern = cache.get(cacheKey)
  if (!pattern) {
    pattern = wordListPattern([...LISTS[key].en, ...LISTS[key].ru])
    cache.set(cacheKey, pattern)
  }
  return pattern
}
